# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d4ec594ac97b7ccbe348f3e02970df6eaf669c2571dd0b7f3139224c904269e47251a45ef269dd5c024f47d94453b6d1f9140c2c0f68ee973a726a9aa16ffb

test:
  secret_key_base: 925b434ab05eb8bfb30dba241b36e1f31d9385dd5ff9c604d3c5320643c5aef929384c4e60ac9322cd82ec0644cbfbf05e1015d0e664e892502a408b5a04701b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
