FROM ft_rails:on-build

LABEL Description="Ruby layer test"

# Build Process
# (1): docker build -t ft_docker/ft_rails .
# (2): docker build -t local/myrails -f Dockerfile.test .
# (3): docker run -p 3000:3000 --rm local/myrails

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
